function s = renyiFlux(n, alpha, X, w)
    s = X.^((-1/4).*alpha.^2.*n.^(-1).*pi.^(-2))+w.*X.^((-1/4).*n.^(-1).*( ...
    alpha+(-2).*pi).^2.*pi.^(-2))+w.*X.^((-1/4).*n.^(-1).*pi.^(-2).*( ...
    alpha+2.*pi).^2);
end