path(path, ['/home/noa/TN/MPSPACK_v3.1'])
startup
path(path, [pwd '/adiabatic'])
path(path, [pwd '/DMRG'])
path(path, [pwd '/exact'])
path(path, [pwd '/theo'])
path(path, [pwd '/fitgui'])
path(path, [pwd '/meas'])
path(path, [pwd '/kondoRF'])
path(path, [pwd '/TR'])
path(path, ['/home/noa/RIPHQuenchProject'])