function X = getOnePointFunc(t, epsilon, L)
    vF = 2*sin(pi * (L/2 + 1) / (L+1));
    X = abs(pi .* sinh(pi/L * 2 * epsilon) ./ ...
        (2 .* sinh(pi / L .* (epsilon + 1i .* vF .* t)) .* ...
         sinh(pi / L .* (epsilon - 1i.*vF.*t))));
end