function s = stheo(L1, L2, NA)
% derivation in salpha.nb
    K = 1;
    c = 1;
    s = (1/12).*K.^(-3/2).*L2.^((-1/2).*K).*log(L2).^(-3/2).*(sqrt(-1).* ...
         2.^(1/2).*exp(1).^((sqrt(-1)*(-1)).*NA.*pi).*(dawson(2.^(-1/2).* ...
          K.^(-1/2).*log(L2).^(-1/2).*(NA.*pi+(sqrt(-1)*(-1)).*K.*log(L2)))+ ...
          (-1).*exp(1).^((sqrt(-1)*2).*NA.*pi).*dawson(2.^(-1/2).*K.^(-1/2) ...
          .*log(L2).^(-1/2).*(NA.*pi+sqrt(-1).*K.*log(L2)))).*(3.*NA.^2.* ...
          pi.^2+K.*((-3)+c.*log(L1)).*log(L2))+6.*K.^(1/2).*log(L2).^( ...
          1/2).*(K.*cos(NA.*pi).*log(L2)+(-1).*NA.*pi.*sin(NA.*pi)));
end